import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#f4f2ff',
  },
  backBtn: {
    position: 'absolute',
    top: 56,
    left: 16,
    zIndex: 10,
    backgroundColor: 'rgba(20,10,50,0.45)',
    borderRadius: 20,
    padding: 8,
  },
  scroll: {
    flex: 1,
  },
  heroImage: {
    width: '100%',
    height: 260,
    backgroundColor: '#e8e4ff',
  },
  contentCard: {
    backgroundColor: '#f4f2ff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -24,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 48,
  },
  meta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
  },
  categoryPill: {
    backgroundColor: '#6A62B7',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  categoryText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'SourceSans3-Regular',
    fontWeight: '700',
  },
  readTime: {
    color: '#9993c8',
    fontSize: 13,
    fontFamily: 'SourceSans3-Regular',
  },
  title: {
    fontSize: 24,
    color: '#222',
    fontFamily: 'Merriweather_36pt-Bold',
    lineHeight: 34,
    marginBottom: 20,
  },
  h1: {
    fontSize: 22,
    color: '#222',
    fontFamily: 'Merriweather_36pt-Bold',
    lineHeight: 30,
    marginBottom: 16,
    marginTop: 8,
  },
  h2: {
    fontSize: 18,
    color: '#3d3880',
    fontFamily: 'Merriweather_36pt-Bold',
    lineHeight: 26,
    marginTop: 22,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 16,
    color: '#333',
    fontFamily: 'SourceSans3-Regular',
    lineHeight: 26,
    marginBottom: 14,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 6,
    paddingLeft: 4,
  },
  bulletDot: {
    fontSize: 16,
    color: '#6A62B7',
    marginRight: 8,
    lineHeight: 26,
  },
  bulletText: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    fontFamily: 'SourceSans3-Regular',
    lineHeight: 26,
  },
  bulletGroup: {
    marginBottom: 14,
  },
  affiliateCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    marginVertical: 14,
    borderWidth: 1,
    borderColor: '#e8e4ff',
    shadowColor: '#6A62B7',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  affiliateTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  affiliateTitle: {
    fontSize: 16,
    color: '#222',
    fontFamily: 'Merriweather_36pt-Bold',
    flex: 1,
    marginRight: 8,
  },
  affiliateBadge: {
    backgroundColor: '#ede9ff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  affiliateBadgeText: {
    fontSize: 11,
    color: '#6A62B7',
    fontFamily: 'SourceSans3-Regular',
    fontWeight: '700',
  },
  affiliateDesc: {
    fontSize: 14,
    color: '#666',
    fontFamily: 'SourceSans3-Regular',
    lineHeight: 20,
    marginBottom: 12,
  },
  affiliateBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  affiliatePrice: {
    fontSize: 15,
    color: '#3d3880',
    fontFamily: 'Merriweather_36pt-Bold',
  },
  affiliateBtn: {
    backgroundColor: '#6A62B7',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  affiliateBtnText: {
    color: '#fff',
    fontSize: 14,
    fontFamily: 'SourceSans3-Regular',
    fontWeight: '700',
  },
});
