import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F7F3FF',
  },
  content: {
    paddingBottom: 36,
  },
  hero: {
    height: 360,
    position: 'relative',
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
  },
  heroOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 52 : 60,
    paddingBottom: 26,
    backgroundColor: 'rgba(17, 12, 36, 0.28)',
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroCopy: {
    gap: 8,
  },
  eyebrow: {
    color: '#F5ECFF',
    fontSize: 13,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontFamily: 'SourceSans3-Regular',
  },
  title: {
    color: '#FFFFFF',
    fontSize: 34,
    lineHeight: 40,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  subtitle: {
    color: '#F5ECFF',
    fontSize: 17,
    lineHeight: 24,
    fontFamily: 'SourceSans3-Regular',
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  statPill: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statPillText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontFamily: 'SourceSans3-Regular',
  },
  sectionCard: {
    marginHorizontal: 18,
    marginTop: 18,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#2B174F',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  sectionLabel: {
    color: '#6A62B7',
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
    fontFamily: 'SourceSans3-Regular',
  },
  sectionTitle: {
    color: '#221A35',
    fontSize: 24,
    lineHeight: 30,
    marginBottom: 10,
    fontFamily: 'Merriweather_24pt-Bold',
  },
  body: {
    color: '#544B68',
    fontSize: 16,
    lineHeight: 25,
    fontFamily: 'SourceSans3-Regular',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 14,
  },
  listBullet: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EFE9FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  listText: {
    flex: 1,
    color: '#352B49',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: 'SourceSans3-Regular',
  },
  splitRow: {
    flexDirection: 'row',
    marginHorizontal: 18,
    gap: 14,
  },
  splitCard: {
    flex: 1,
    backgroundColor: '#DCCFFF',
    borderRadius: 22,
    padding: 18,
    marginTop: 18,
  },
  splitTitle: {
    color: '#2D2444',
    fontSize: 19,
    lineHeight: 24,
    marginBottom: 8,
    fontFamily: 'Merriweather_24pt-Bold',
  },
  splitBody: {
    color: '#4D4564',
    fontSize: 15,
    lineHeight: 22,
    fontFamily: 'SourceSans3-Regular',
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    backgroundColor: '#F7F3FF',
  },
  stateTitle: {
    marginTop: 14,
    marginBottom: 8,
    color: '#231B36',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'Merriweather_24pt-Bold',
  },
  stateText: {
    color: '#5F576F',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    fontFamily: 'SourceSans3-Regular',
  },
});
