import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    marginTop: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 18,
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#222',
    fontFamily: 'Merriweather_36pt-Bold',
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#eaeaea',
  },
  searchWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 18,
    marginHorizontal: 20,
    paddingHorizontal: 16,
    height: 48,
    marginBottom: 18,
  },
  searchInput: {
    flex: 1,
    fontSize: 18,
    color: '#222',
    fontFamily: 'SourceSans3-Regular',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#222',
    marginLeft: 20,
    marginBottom: 10,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  sectionTitleFeatured: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    marginLeft: 20,
    marginBottom: 10,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  recommendedCard: {
    width: 335,
    height: 253,
    backgroundColor: '#fff',
    borderRadius: 22,
    marginLeft: 20,
    marginRight: 10,
    marginBottom: 8,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  recommendedCardContent: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    borderTopRightRadius: 22,
    borderTopLeftRadius: 22,
    padding: 14,
    marginTop: -20,
  },
  destinationCardContent: {
    backgroundColor: '#fff',
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    borderTopRightRadius: 22,
    borderTopLeftRadius: 22,
    padding: 14,
    marginTop: -20,
  },
  recommendedCardTitle: {
    color: '#6A62B7',
    fontSize: 20,
    marginBottom: 4,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    color: '#888',
    fontSize: 14,
    marginLeft: 4,
    fontFamily: 'SourceSans3-Regular',
  },
  heartIcon: {
    position: 'absolute',
    top: 10,
    right: 14,
    backgroundColor: 'rgba(0,0,0,0.28)',
    borderRadius: 16,
    padding: 4,
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#e0d8f7',
    marginHorizontal: 3,
  },
  dotActive: {
    width: 18,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#6A62B7',
    marginHorizontal: 3,
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 8,
    marginBottom: 8,
  },
  viewAll: {
    color: '#6A62B7',
    fontWeight: 'bold',
    fontSize: 15,
    fontFamily: 'SourceSans3-Regular',
  },
  popularRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 18,
  },

popularCard: {
  width: 180,
  marginRight: 16,
  backgroundColor: '#fff',
  borderRadius: 16,
  overflow: 'hidden',
  borderWidth: 1,
  borderColor: '#EFEFEF',
  elevation: 2,
  shadowColor: '#000',
  shadowOpacity: 0.07,
  shadowRadius: 8,
  padding: 8,
  alignItems: 'center',
},
popularCardImage: {
  width: 164,
  height: 110,
  borderRadius: 12,
  marginBottom: 8,
},
  popularCardTitle: {
    fontSize: 16,
    color: '#6A62B7',
    marginBottom: 6,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  heartIconSmall: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.28)',
    borderRadius: 12,
    padding: 2,
  },
  articlesRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 18,
  },
  articleCard: {
    flex: 1,
    height: 90,
    backgroundColor: '#b7aee2',
    borderRadius: 16,
    marginRight: 12,
    marginLeft: 0,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 16,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 32,
    marginHorizontal: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
  },
  navItemActive: {
    flex: 1,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: '#6A62B7',
    paddingBottom: 2,
  },
  featuredTripCard: {
    marginHorizontal: 20,
    marginBottom: 24,
    borderRadius: 24,
    backgroundColor: '#fff',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EFEFEF',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  featuredTripImage: {
    width: '100%',
    height: 160,
  },
  recommendedTripImage: {
    width: '100%',
    height: '100%',
  },
  featuredTripContent: {
    padding: 18,
  },
  featuredTripTitle: {
    fontSize: 22,
    color: '#6A62B7',
    marginBottom: 8,
    fontFamily: 'Merriweather_36pt-Bold',
  },
  featuredTripSubtitle: {
    fontSize: 15,
    color: '#888',
    marginBottom: 16,
    fontFamily: 'SourceSans3-Regular',
    lineHeight: 22,
  },
  featuredTripButton: {
    backgroundColor: '#6A62B7',
    borderRadius: 24,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  featuredTripButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    fontFamily: 'Merriweather_36pt-Bold',
  },
  // Add to your discoverScreenStyles.js or .ts
destinationCardImage: {
  width: '100%',
  height: 180,
  borderRadius: 24,
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
},
  destinationCard: {
    width: 180,
    height: 180,
    borderRadius: 22,
    marginLeft: 20,
    marginRight: 10,
    marginBottom: 8,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },

});