import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 24,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  paginationRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
    position: 'relative',
    minHeight: 56,
    marginTop: 24,
  },
  arrowText: {
    color: '#fff',
    fontSize: 26,
    fontWeight: 'light',
  },
  imageWrapper: {
    width: '98%',
    alignSelf: 'center',
    aspectRatio: 1,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    overflow: 'hidden',
    marginBottom: 24,
    marginTop: 5,
  },
  image: {
    width: '100%',
    height: '100%',
  },
  heading: {
    color: '#2C2C2C',
    fontFamily: 'Merriweather_36pt-Bold',
    fontSize: 36,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: undefined,
    marginTop: 8,
    marginBottom: 20,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginLeft: 38,
  },
  subtitle: {
    color: '#2C2C2C',
    fontFamily: 'SourceSans3-Regular',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 32,
    marginBottom: 32,
    textAlign: 'left',
    alignSelf: 'flex-start',
    marginLeft: 38,
    maxWidth: 293,
  },
  pagination: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#B9B1FF',
    marginHorizontal: 4,
  },
  dotActive: {
    width: 24,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#897CFF',
    marginHorizontal: 4,
  },
  buttonWrapper: {
    position: 'absolute',
    right: 35,
    backgroundColor: '#6A62B7',
    borderRadius: 40,
    width: 90,
    height: 55,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowIcon: {
    color: '#6A62B7',
  },
    thirdPageButtonRow: {
    alignItems: 'center',
    marginTop: 24,
    width: '100%',
  },
  thirdPageButton: {
    backgroundColor: '#6A62B7',
    borderRadius: 40,
    width: 322,
    height: 70.714,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arrowTextLarge: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
  },
  letsGoText: {
  color: '#fff',
  letterSpacing: 1,
  fontFamily: 'Merriweather_36pt-Bold',
  fontSize: 24,
  fontStyle: 'normal',
  fontWeight: '700',
},
});