import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
 topBar: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-start',
  marginTop: 16,
  marginBottom: 8,
  paddingHorizontal: 16,
  position: 'relative', // Needed for absolute centering
},
backArrow: {
  padding: 8,
  marginRight: 8,
  backgroundColor: 'rgba(255,255,255,0.7)',
  borderRadius: 20,
  zIndex: 2,
},
progressBarAbsoluteContainer: {
  position: 'absolute',
  left: 0,
  right: 0,
  top: 0,
  bottom: 0,
  alignItems: 'center',
  justifyContent: 'center',
  zIndex: 1,
},
progressBarWrapper: {
  alignItems: 'center',
  justifyContent: 'center',
  height: 12,
  width: 180,
  position: 'relative',
},
progressBarBg: {
  width: '100%',
  height: 12,
  borderRadius: 6,
  backgroundColor: '#eaeaea',
  position: 'absolute',
  top: 0,
  left: 0,
},
progressBarFill: {
  width: '40%',
  height: 12,
  borderRadius: 6,
  backgroundColor: '#6A62B7',
  position: 'absolute',
  top: 0,
  left: 0,
},
  scrollContent: {
    paddingHorizontal: 24,
    paddingBottom: 120,
  },
  heading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#222',
    fontFamily: 'Merriweather_36pt-Bold',
    marginBottom: 12,
    marginTop: 15,
    alignSelf: 'stretch',
  },
  headingEmoji: {
    fontSize: 32,
  },
  subheading: {
    fontSize: 18,
    color: '#888',
    fontFamily: 'SourceSans3-Regular',
    marginBottom: 32,
    lineHeight: 28,
    alignSelf: 'stretch',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fafafa',
    borderRadius: 22,
    paddingHorizontal: 18,
    height: 56,
    marginBottom: 24,
  },
  searchIcon: {
    fontSize: 22,
    color: '#bdbdbd',
    marginRight: 10,
  },
  helperText: {
  color: '#888',
  fontSize: 16,
  textAlign: 'center',
  marginBottom: 8,
  fontFamily: 'SourceSans3-Regular',
},
  searchInput: {
    flex: 1,
    fontSize: 20,
    color: '#222',
    fontFamily: 'SourceSans3-Regular',
  },
prefsGrid: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  justifyContent: 'center',
  gap: 10,
  paddingTop: 4,
},
prefsRow: {
  // kept for compatibility but unused
},
prefButton: {
  flexDirection: 'row',
  alignItems: 'center',
  borderWidth: 1.5,
  borderColor: '#e0e0e0',
  borderRadius: 100,
  paddingVertical: 10,
  paddingHorizontal: 16,
  backgroundColor: '#fafafa',
},
prefButtonSelected: {
  borderColor: '#6A62B7',
  backgroundColor: '#6A62B7',
},
prefText: {
  fontSize: 15,
  color: '#333',
  fontFamily: 'SourceSans3-Regular',
  fontWeight: '600',
},
prefTextSelected: {
  color: '#fff',
  fontWeight: '700',
},
prefEmoji: {
  fontSize: 15,
  marginLeft: 5,
},
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    backgroundColor: '#fff',
    paddingVertical: 24,
    paddingHorizontal: 24,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  continueButton: {
    backgroundColor: '#6A62B7',
    borderRadius: 32,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    fontFamily: 'Merriweather_36pt-Bold',
  },
});